buildsrht/blueprints/jobs.py
from ansi2html import Ansi2HTMLConverter
from buildsrht.manifest import Manifest
from buildsrht.rss import generate_feed
from buildsrht.runner import submit_build, requires_payment
from buildsrht.search import apply_search
from buildsrht.types import Job, JobStatus, Task, TaskStatus, User, Visibility
from datetime import datetime, timedelta
from flask import Blueprint, render_template, request, abort, redirect
from flask import Response, url_for
from markupsafe import Markup, escape
from prometheus_client import Counter
from srht.cache import get_cache, set_cache
from srht.config import cfg
from srht.database import db
from srht.flask import paginate_query, session
from srht.oauth import current_user, loginrequired, UserType
from srht.redis import redis
from srht.validation import Validation
import sqlalchemy as sa
import hashlib
import requests
import yaml
import json
import textwrap

jobs = Blueprint("jobs", __name__)

metrics = type("metrics", tuple(), {
    c.describe()[0].name: c
    for c in [
        Counter("buildsrht_logcache_hit", "Number of log cache hits"),
        Counter("buildsrht_logcache_miss", "Number of log cache misses"),
    ]
})

requests_session = requests.Session()

def get_access(job, user=None):
    user = user or current_user

    # Anonymous
    if not user:
        if job.visibility == Visibility.PRIVATE:
            return False
        return True

    # Owner
    if user.id == job.owner_id:
        return True

    if job.visibility == Visibility.PRIVATE:
        return False
    return True

def tags(tags):
    if not tags:
        return list()
    previous = list()
    results = list()
    for tag in tags.split("/"):
        results.append({
            "name": tag,
            "url": "/" + "/".join(previous + [tag])
        })
        previous.append(tag)
    return results

status_map = {
    JobStatus.pending: "text-info",
    JobStatus.queued: "text-info",
    JobStatus.success: "text-success",
    JobStatus.failed: "text-danger",
    JobStatus.running: "text-info icon-spin",
    JobStatus.timeout: "text-danger",
    JobStatus.cancelled: "text-warning",
    TaskStatus.success: "text-success",
    TaskStatus.failed: "text-danger",
    TaskStatus.running: "text-primary icon-spin",
    TaskStatus.pending: "text-info",
    TaskStatus.skipped: "text-muted",
}

icon_map = {
    JobStatus.pending: "clock",
    JobStatus.queued: "clock",
    JobStatus.success: "check",
    JobStatus.failed: "times",
    JobStatus.running: "circle-notch",
    JobStatus.timeout: "clock",
    JobStatus.cancelled: "times",
    TaskStatus.success: "check",
    TaskStatus.failed: "times",
    TaskStatus.running: "circle-notch",
    TaskStatus.pending: "circle",
    TaskStatus.skipped: "minus",
}

def get_jobs(jobs, terms):
    jobs = jobs.order_by(Job.created.desc())
    if terms:
        jobs = apply_search(jobs, terms)
    return jobs

def jobs_for_feed(jobs):
    terms = request.args.get("search")
    try:
        jobs = get_jobs(jobs, terms)
    except ValueError:
        jobs = jobs.filter(False)

    if terms is not None and "status:" not in terms:
        # by default, return only terminated jobs in feed
        terminated_statuses = [
            JobStatus.success,
            JobStatus.cancelled,
            JobStatus.failed,
            JobStatus.timeout,
        ]
        jobs = jobs.filter(Job.status.in_(terminated_statuses))
    return jobs, terms

def jobs_page(jobs, sidebar="sidebar.html", **kwargs):
    search = request.args.get("search")
    search_error = None

    try:
        jobs = (get_jobs(jobs, search))
    except ValueError as ex:
        search_error = str(ex)

    jobs = jobs.options(sa.orm.joinedload(Job.tasks))
    jobs, pagination = paginate_query(jobs)
    return render_template("jobs.html",
        jobs=jobs, status_map=status_map, icon_map=icon_map, tags=tags,
        sort_tasks=lambda tasks: sorted(tasks, key=lambda t: t.id),
        sidebar=sidebar, search=search, search_error=search_error,
        **pagination, **kwargs)

def jobs_feed(jobs, title, endpoint, **urlvalues):
    jobs, terms = jobs_for_feed(jobs)
    if terms is not None:
        title = f"{title} (filtered by: {terms})"
    description = title
    origin = cfg("builds.sr.ht", "origin")
    assert "search" not in urlvalues
    if terms is not None:
        urlvalues["search"] = terms
    link = origin + url_for(endpoint, **urlvalues)
    jobs=jobs.options(sa.orm.joinedload(Job.owner))
    return generate_feed(jobs, title, link, description)

badge_success = """
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="124" height="20"><linearGradient id="b" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="a"><rect width="124" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#a)"><path fill="#555" d="M0 0h71v20H0z"/><path fill="#4c1" d="M71 0h53v20H71z"/><path fill="url(#b)" d="M0 0h124v20H0z"/></g><g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="110"> <text x="365" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="610">__NAME__</text><text x="365" y="140" transform="scale(.1)" textLength="610">__NAME__</text><text x="965" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="430">success</text><text x="965" y="140" transform="scale(.1)" textLength="430">success</text></g></svg>
"""

badge_failure = """
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="124" height="20"><linearGradient id="b" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="a"><rect width="124" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#a)"><path fill="#555" d="M0 0h71v20H0z"/><path fill="#e05d44" d="M71 0h53v20H71z"/><path fill="url(#b)" d="M0 0h124v20H0z"/></g><g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="110"> <text x="365" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="610">__NAME__</text><text x="365" y="140" transform="scale(.1)" textLength="610">__NAME__</text><text x="965" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="430">failure</text><text x="965" y="140" transform="scale(.1)" textLength="430">failure</text></g></svg>
"""

badge_unknown = """
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="132" height="20"><linearGradient id="b" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="a"><rect width="132" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#a)"><path fill="#555" d="M0 0h71v20H0z"/><path fill="#9f9f9f" d="M71 0h61v20H71z"/><path fill="url(#b)" d="M0 0h132v20H0z"/></g><g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="110"> <text x="365" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="610">__NAME__</text><text x="365" y="140" transform="scale(.1)" textLength="610">__NAME__</text><text x="1005" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="510">unknown</text><text x="1005" y="140" transform="scale(.1)" textLength="510">unknown</text></g> </svg>
"""

def svg_page(jobs):
    name = request.args.get("name",
            default=cfg("sr.ht", "site-name"))
    job = (get_jobs(jobs, None)
        .filter(Job.status.in_([
            JobStatus.success,
            JobStatus.failed,
            JobStatus.timeout]))
        .first())
    if not job:
        badge = badge_unknown.replace("__NAME__", escape(name))
    elif job.status == JobStatus.success:
        badge = badge_success.replace("__NAME__", escape(name))
    else:
        badge = badge_failure.replace("__NAME__", escape(name))
    return badge

@jobs.route("/")
def index():
    if not current_user:
        return render_template("index-logged-out.html")
    origin = cfg("builds.sr.ht", "origin")
    rss_feed = {
        "title": f"{current_user.username}'s jobs",
        "url": origin + url_for("jobs.user_rss",
                                username=current_user.username,
                                search=request.args.get("search")),
    }
    return jobs_page(
            Job.query.filter(Job.owner_id == current_user.id),
            "index.html", rss_feed=rss_feed)


@jobs.route("/submit")
@loginrequired
def submit_GET():
    if request.args.get("manifest"):
        manifest = request.args.get("manifest")
    else:
        manifest = session.pop("manifest", default=None)
    if request.args.get("note"):
        note = request.args.get("note")
    else:
        note = session.pop("note", default=None)
    note_rows = len(note.splitlines()) if isinstance(note, str) else 1
    status = 200
    payment_required = requires_payment(current_user)
    if payment_required:
        status = 402
    return render_template("submit.html",
            manifest=manifest,
            note=note,
            note_rows=note_rows,
            payment_required=payment_required), status

def addsuffix(note: str, suffix: str) -> str:
    """
    Given a note and a suffix, return the note with the suffix concatenated/

    The returned string is guaranteed to fit in the Job.note DB field.
    """
    maxlen = Job.note.prop.columns[0].type.length
    assert len(suffix) + 1 <= maxlen, f"Suffix was too long ({len(suffix)})"
    if note.endswith(suffix) or not note:
        return note
    result = f"{note} {suffix}"
    if len(result) <= maxlen:
        return result
    note = textwrap.shorten(note, maxlen - len(suffix) - 1, placeholder="…")
    return f"{note} {suffix}"

@jobs.route("/resubmit/<int:job_id>")
@loginrequired
def resubmit_GET(job_id):

buildsrht/blueprints/secrets.py
from buildsrht.types import Secret, SecretType
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization
from flask import Blueprint, render_template, request, redirect, abort
from srht.database import db
from srht.flask import session
from srht.oauth import current_user, loginrequired
from srht.validation import Validation

secrets = Blueprint('secrets', __name__)

@secrets.route("/secrets")
@loginrequired
def secrets_GET():
    message = session.get("message")
    if message:
        del session["message"]
    # TODO: Pagination I guess
    secrets = Secret.query.filter(Secret.user_id == current_user.id).all()
    return render_template("secrets.html", message=message, secrets=secrets)

@secrets.route("/secrets", methods=["POST"])
@loginrequired
def secrets_POST():
    valid = Validation(request)

    name = valid.optional("name")
    secret_type = valid.require("secret_type", friendly_name="Secret Type")
    valid.expect(not name or 3 < len(name) < 512,
            "Name must be between 3 and 512 characters", field="name")
    if secret_type is not None:
        try:
            secret_type = SecretType(secret_type)
        except:
            valid.error("{} is not a valid secret type".format(secret_type),
                    field="secret_type")

    if secret_type == SecretType.plaintext_file:
        _secret = valid.optional("secret")
        secret_file = valid.optional("file-file", max_file_size=16384)
        for f in ["secret", "file-file"]:
            valid.expect(bool(_secret) ^ bool(secret_file),
                    "Either secret text or file have to be provided", field=f)
    else:
        _secret = valid.require("secret", friendly_name="Secret")

    if secret_type in (SecretType.plaintext_file, SecretType.ssh_key):
        if _secret:
            _secret = _secret.replace('\r\n', '\n')
            if not _secret.endswith('\n'):
                _secret += '\n'
        elif secret_type == SecretType.plaintext_file:
            _secret = secret_file

    if isinstance(_secret, str):
        _secret = _secret.encode()

    if not valid.ok:
        secrets = Secret.query.filter(Secret.user_id == current_user.id).all()
        return render_template("secrets.html", secrets=secrets, **valid.kwargs)

    secret = Secret(current_user, secret_type)

    if secret_type == SecretType.plaintext_file:
        file_path = valid.require("file-path", friendly_name="Path")
        file_mode = valid.require("file-mode", friendly_name="Mode")
        if not valid.ok:
            secrets = Secret.query.filter(Secret.user_id == current_user.id).all()
            return render_template("secrets.html", secrets=secrets, **valid.kwargs)
        try:
            file_mode = int(file_mode, 8)
        except:
            valid.error("Must be specified in octal",
                    field="file-mode")
        if not valid.ok:
            secrets = Secret.query.filter(Secret.user_id == current_user.id).all()
            return render_template("secrets.html", secrets=secrets, **valid.kwargs)
        secret.path = file_path
        secret.mode = file_mode
    if not valid.ok:
        secrets = Secret.query.filter(Secret.user_id == current_user.id).all()
        return render_template("secrets.html", secrets=secrets, **valid.kwargs)

    secret.name = name
    secret.secret = _secret

    db.session.add(secret)
    db.session.commit()

    session["message"] = "Successfully added secret {}.".format(secret.uuid)
    return redirect("/secrets")

@secrets.route("/secret/delete/<uuid>")
@loginrequired
def secret_delete_GET(uuid):
    secret = Secret.query.filter(Secret.uuid == uuid).first()
    if not secret:
        abort(404)
    if secret.user_id != current_user.id:
        abort(401)

    return render_template("secret_delete.html", secret=secret)


@secrets.route("/secret/delete", methods=["POST"])
@loginrequired
def secret_delete_POST():
    valid = Validation(request)

    uuid = valid.require("uuid")
    if not uuid:
        abort(404)

    secret = Secret.query.filter(Secret.uuid == uuid).first()
    if not secret:
        abort(404)
    if secret.user_id != current_user.id:
        abort(401)

    name = secret.name
    db.session.delete(secret)
    db.session.commit()

    session["message"] = "Successfully removed secret {}{}.".format(uuid,
            " ({})".format(name) if name else "")
    return redirect("/secrets")

buildsrht/blueprints/settings.py
from flask import Blueprint, current_app, render_template, request, url_for, abort, redirect
from flask import current_app
from srht.database import db
from srht.oauth import current_user, loginrequired
from srht.validation import Validation
from buildsrht.types import Job, Visibility

settings = Blueprint("settings", __name__)

@settings.route("/~<username>/job/<int:job_id>/settings/details")
@loginrequired
def details_GET(username, job_id):
    job = Job.query.get(job_id)
    if not job:
        abort(404)
    if current_user.id != job.owner_id:
        abort(404)
    return render_template("job-details.html",
        view="details", job=job)

@settings.route("/~<username>/job/<int:job_id>/settings/details", methods=["POST"])
@loginrequired
def details_POST(username, job_id):
    job = Job.query.get(job_id)
    if not job:
        abort(404)
    if current_user.id != job.owner_id:
        abort(404)

    valid = Validation(request)
    visibility = valid.require("visibility")
    if not valid.ok:
        return render_template("job-details.html",
            job=job, **valid.kwargs), 400

    # TODO: GraphQL mutation to update job details
    job.visibility = visibility
    db.session.commit()

    return redirect(url_for("settings.details_GET",
        username=job.owner.username,
        job_id=job.id))

buildsrht/templates/index-logged-out.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
  <div class="col-md-8">
    <p>
      Welcome to <strong>{{domain}}</strong>! This provides continuous
      integration services for
      <a href="{{cfg("sr.ht", "site-info")}}">
        {{cfg("sr.ht", "site-name")}}</a>,
      {{cfg("sr.ht", "site-blurb")}}.
      Features of this service include:
    </p>
    <ul>
      <li>Runs fully virtualised builds on various Linux distros and BSDs</li>
      <li>Run anonymous jobs that aren't tied to a repository</li>
      <li>Post-build triggers for email, webhooks, etc</li>
      <li>Powerful API for complex build scenarios</li>
    </ul>
    <a
      class="btn btn-primary"
      href="{{get_origin("meta.sr.ht", external=True)}}/register"
    >Register here {{icon('caret-right')}}</a>
    or
    <a href="{{oauth_url}}">
      Log in {{icon('caret-right')}}
    </a>
    to get started.
  </div>
</div>
{% endblock %}

buildsrht/templates/index.html
<div class="sidebar">
  <p>
    Welcome back, {{ current_user.username }}! This is your build service.
    Documentation for its use is
    <a href="https://man.sr.ht/builds.sr.ht">available here</a>.
  </p>
  <a class="btn btn-primary btn-block" href="/submit">
    Submit manifest {{icon("caret-right")}}
  </a>
  <a class="btn btn-default btn-block" href="/secrets">
    Manage secrets {{icon("caret-right")}}
  </a>
</div>

buildsrht/templates/job-details.html
{% extends "settings.html" %}
{% block title %}
<title>Configure {{url_for("jobs.user", username=job.owner.username)}}/#{{job.id}}
  &mdash; {{ cfg("sr.ht", "site-name") }}</title>
{% endblock %}
{% block content %}
<form class="row" method="POST">
  {{csrf_token()}}
  <div class="col-md-6 d-flex flex-column">
    <fieldset class="form-group">
      <legend>Job Visibility</legend>
      <div class="form-check">
        <label class="form-check-label">
          <input
            class="form-check-input"
            type="radio"
            name="visibility"
            value="PUBLIC"
            {% if job.visibility.value == "PUBLIC" %}
            checked
            {% endif %}
            > Public
          <small id="visibility-public-help" class="form-text text-muted">
            Shown on your profile page
          </small>
        </label>
      </div>
      <div class="form-check">
        <label
            class="form-check-label"
            title="Visible to anyone with the link, but not shown on your profile"
          >
          <input
            class="form-check-input"
            type="radio"
            name="visibility"
            value="UNLISTED"
            {% if job.visibility.value == "UNLISTED" %}
            checked
            {% endif %}
            > Unlisted
          <small id="visibility-unlisted-help" class="form-text text-muted">
            Visible to anyone who knows the URL, but not shown on your profile
          </small>
        </label>
      </div>
      <div class="form-check">
        <label
          class="form-check-label"
          title="Only visible to you and your collaborators"
        >
          <input
            class="form-check-input"
            type="radio"
            name="visibility"
            value="PRIVATE"
            {% if job.visibility.value == "PRIVATE" %}
            checked
            {% endif %}
            > Private
          <small id="visibility-unlisted-help" class="form-text text-muted">
            Only visible to you and your collaborators
          </small>
        </label>
      </div>
    </fieldset>
    {{ valid.summary() }}
    <span class="pull-right">
      <button type="submit" class="btn btn-primary">
        Save {{icon("caret-right")}}
      </button>
    </span>
  </div>
</form>
{% endblock %}

buildsrht/templates/job.html
{% extends "layout-full.html" %}
{% block title %}
<title>
  build #{{ job.id }} - {{ job.status.value }}
</title>
{% endblock %}
{% block head %}
{% if job.status.value == "pending" or job.status.value == "queued" %}
<meta id="refresh" http-equiv="refresh" content="10">
{% endif %}
{% if job.status.value == "running" %}
<meta id="refresh" http-equiv="refresh" content="5">
{% endif %}
{% endblock %}
{% block body %} 
<div class="header-tabbed">
  <div class="container-fluid">
    <h2>
      <a href="{{ url_for("jobs.user", username=job.owner.username) }}">{{ job.owner }}</a>/<wbr
     >#{{ job.id }}
    </h2>
    <ul class="nav nav-tabs">
      {% if job.visibility.value != "PUBLIC" %}
      <li
        class="nav-item nav-text vis-{{job.visibility.value.lower()}}"
        {% if job.visibility.value == "UNLISTED" %}
        title="This job is only visible to those who know the URL."
        {% elif job.visibility.value == "PRIVATE" %}
        title="This job is only visible to those who were invited to view it."
        {% endif %}
      >
        {% if job.visibility.value == "UNLISTED" %}
        Unlisted
        {% elif job.visibility.value == "PRIVATE" %}
        Private
        {% endif %}
      </li>
      {% endif %}
      {% if current_user and current_user.id == job.owner_id %}
      <li class="nav-item">
        <a class="nav-link" href="{{url_for("settings.details_GET",
          username=job.owner.username,
          job_id=job.id)}}"
        >settings</a>
      </li>
      {% endif %}
    </ul>
  </div>
</div>
<div class="container-fluid">
  <section class="row">
    <div class="col-lg-3 col-md-12">
      <h2>
        {{icon(icon_map.get(job.status), cls=status_map.get(job.status, ""))}}
        {{ job.status.value }}
      </h2>
      <dl>
        {% if job.note %}
        <p>{{ job.note | md }}</p>
        {% endif %}
        <dt>Owner</dt>
        <dd>
          <a href="/~{{ job.owner.username }}">
            ~{{ job.owner.username }}
          </a>
        </dd>
        <dt>Created</dt>
        <dd>{{ job.created | date }}</dd>
        <dt>Updated</dt>
        <dd>{{ job.updated | date }}</dd>
        <dt>Build manifest</dt>
        <dd><a href="/api/jobs/{{ job.id }}/manifest">view manifest »</a></dd>
      </dl>
      {% if current_user and job.status.value in [
        "success", "failed", "timeout", "cancelled"
      ] and not payment_required %}
      <form style="margin-bottom: 0.5rem" method="POST" action="/submit">
        {{csrf_token()}}
        <input
          type="hidden"
          name="note"
          value="Resubmission of build [#{{job.id}}](/~{{ job.owner.username }}/job/{{ job.id }})"
        />
        <button class="btn btn-primary btn-block">
          Resubmit build
          {{ icon("caret-right") }}
        </button>
        <input type="hidden" name="manifest" value="{{job.manifest}}" />
      </form>
      <form>
        <a
          href="{{ url_for("jobs.resubmit_GET", job_id=job.id) }}"
          class="btn btn-default btn-block"
        >
          Edit &amp; resubmit
          {{ icon("caret-right") }}
        </a>
      </form>
      {% elif (current_user and
        (current_user.id == job.owner_id or current_user.user_type.value == "admin") and
        job.status.value == "running") %}
      <form method="POST" action="{{ url_for("jobs.cancel", job_id=job.id) }}">
        {{csrf_token()}}
        <button class="btn btn-danger btn-block">
          Cancel build
        </button>
      </form>
      {% endif %}
      {% if any(job.artifacts) %}
      <h4>Artifacts</h4>
      <table class="table table-sm">
      {% for artifact in job.artifacts %}
        <tr>
          <td style="
              max-width: 200px;
              overflow-x: hidden;
              text-overflow: ellipsis;
          ">
            <span title="{{artifact.path}}">
              {{artifact.name}}
            </span>
          </td>
          <td>
            {{naturalsize(artifact.size, binary=True)}}
          </td>
          <td>
            {% if artifact.created > min_artifact_date %}
            <a
              rel="noopener nofollow"
              href="{{artifact.url}}"
            >download »</a>
            {% else %}
            <span class="text-muted">(pruned after 90 days)</span>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
      </table>
      <div class="alert alert-warning">
        Build artifacts are pruned after 90 days.
      </div>
      {% endif %}
      <h4>Tasks</h4>
      <table class="table table-sm">
        <tr class="text-muted">
          <td></td>
          <td>
            <a href="#setup">view log »</a>
          </td>
        </tr>
      {% for task in sort_tasks(job.tasks) %}
        <tr>
          <td>
            <span title="{{ task.status.value }}">
              {{icon(icon_map.get(task.status), cls=status_map.get(task.status, ""))}}
              {{task.name}}
            </span>
          </td>
          <td>
            <a href="#task-{{ task.name }}">view log »</a>
          </td>
        </tr>
      {% endfor %}
      </table>
      <a class="to-bottom" href="#bottom">go to bottom »</a><br>
      <a class="to-top" href="#">go to top »</a>
    </div>
    <div class="col-lg-9 col-md-12">
      {% if current_user and current_user.id == job.owner_id %}
      {% if (job.status.value == "failed" and
          datetime.utcnow() < job.updated + timedelta(minutes=10)) %}
      <div class="alert alert-danger">
        <strong>This build job failed.</strong> You may log into the failed
        build environment within 10 minutes to examine the results with the
        following command:
        <pre
          style="margin-bottom: 0; margin-top: 1rem;"
          >ssh -t {{build_user}}@{{job.runner}} connect {{job.id}}</pre>
      </div>
      {% endif %}
      {% endif %}
      {% if job.status.value != "queued" %}
        {% for log in logs %}
        <details open>
          {% if log["name"] %}
          <summary id="task-{{log["name"]}}">{{ log["name"] }}</summary>
          {% else %}
          <summary id="setup" class="text-muted">setup</summary>
          {% endif %}
          <table class="table-code">
            <tr>
              {{log["log"]}}
            </tr>
          </table>
        </details>
        {% endfor %}
      {% endif %}
      {% if job.status.value == "success" or job.status.value == "failed" %}
      <div class="alert {{ "alert-success" if job.status.value == "success" else "alert-danger" }}">
        Build complete: <strong>{{ job.status.value }}</strong> {{ job.updated | date }}
        (took {{(job.updated - job.created) | date}})
      </div>
      {% endif %}
      <a id="bottom"></a>
    </div>
  </section>
</div>
{% endblock %}
{% block scripts %}
<script>
// @license magnet:?xt=urn:btih:0b31508aeb0634b347b8270c7bee4d411b5d4109&dn=agpl-3.0.txt AGPL-3.0-only
(function() {
  document.addEventListener("DOMContentLoaded", function() {
    var meta_refresh = document.getElementById("refresh");
    if (meta_refresh) {
      var timeout = parseInt(meta_refresh.getAttribute("content"));
      meta_refresh.parentNode.removeChild(meta_refresh);
      window.setTimeout(function() {
        location.reload();
      }, timeout * 1000);
    }
    if (window.location.hash === "#bottom") {
      window.setTimeout(function() {
        document.documentElement.scrollTop = document.documentElement.scrollHeight;
      }, 100);
    }
  });
})();
// @license-end
</script>
{% endblock %}

buildsrht/templates/oauth-error.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
  <section class="col-md-6">
    <h3>An error occured</h3>
    <p>{{ details }}</p>
  </section>
</div>
{% endblock %}

buildsrht/templates/secret_delete.html
{% extends "layout.html" %}
{% block content %}
<section class="row">
  <div class="col-md-12">
    <h2>
      Delete {{ secret.secret_type.pretty_name }}
      "{{ secret.name or secret.uuid }}"
    </h2>
    <dl>
      {% if secret.name %}
      <dt>UUID</dt>
      <dd>{{ secret.uuid }}</dd>
      {% endif %}
      <dt>Created</dt>
      <dd>{{ secret.created | date }}</dd>
      <dt>Last used</dt>
      <dd>{{ secret.updated | date }}</dd>
      {% if secret.secret_type.value == "plaintext_file" %}
      <dt>File</dt>
      <dd>{{ secret.path }} (<i>{{ '%03o' % secret.mode }}</i> mode)</dd>
      {% endif %}
    <dl>
    <form method="POST" action="/secret/delete">
      {{csrf_token()}}
      <input type="hidden" name="uuid" value="{{ secret.uuid }}"></input>
      <button type="submit" class="btn btn-danger">
        Permanently delete secret
      </button>
      <a href="/secrets" class="btn btn-default">
        Cancel, keep secret
      </a>
    </form>
  </div>
</section>
{% endblock %}